# Generated by Django 3.2.12 on 2022-02-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0002_alter_todo_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
